const char index_html[] =
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<meta charset=\"utf-8\" />"
    "</head>"
    "<body>"
    "<p>"
    "AirRifle<br />"
    "<div class=\"svg airRifle\" style=\"width: 500px;\"></div>"
    "</p>"
    "<p>"
    "Rifle50m<br />"
    "<div class=\"svg rifle50m\" style=\"width: 500px;\"></div>"
    "</p>"
    "<script>"
    "(()=>{\"use strict\";var t,e,n,r={227:(t,e)=>{Object.defineProperty(e,\"__esModule\",{value:!0}),e.Settings=void "
    "0;e.Settings=function(){this.svgImageBackgroundColor=\"#FFE4B5\",this.svgImageForegroundColor=\"#000000\",this.svgImageTextFont="
    "\"Arial\"}},835:(t,e)=>{Object.defineProperty(e,\"__esModule\",{value:!0}),e.SvgElement=void "
    "0;e.SvgElement=function(){}},339:(t,e)=>{var n;Object.defineProperty(e,\"__esModule\",{value:!0}),e.SvgElementType=void "
    "0,function(t){t[t.Rectangle=0]=\"Rectangle\",t[t.Circle=1]=\"Circle\",t[t.Text=2]=\"Text\",t[t.Line=3]=\"Line\"}(n||(e.SvgElementType="
    "n={}))},290:(t,e,n)=>{Object.defineProperty(e,\"__esModule\",{value:!0}),e.SvgImage=void 0;var "
    "r=n(835),i=n(339),o=function(){function t(t,e){this.width=t,this.height=e,this.elements=[]}return "
    "t.prototype.addCircle=function(t,e,n,o,g,l){var a=new "
    "r.SvgElement;a.elementType=i.SvgElementType.Circle,a.x=t,a.y=e,a.r=n,o&&(a.fill=o),g&&(a.stroke=g),l&&(a.strokeWidth=l),this.elements."
    "push(a)},t.prototype.addLine=function(t,e,n,o,g,l,a){var c=new "
    "r.SvgElement;c.elementType=i.SvgElementType.Line,c.x=t,c.y=e,c.x2=n,c.y2=o,g&&(c.fill=g),l&&(c.stroke=l),a&&(c.strokeWidth=a),this."
    "elements.push(c)},t.prototype.addRectangle=function(t,e,n,o,g){var l=new "
    "r.SvgElement;l.elementType=i.SvgElementType.Rectangle,l.x=t,l.y=e,l.width=n,l.height=o,g&&(l.fill=g),this.elements.push(l)},t."
    "prototype.addText=function(t,e,n,o,g,l){var a=new "
    "r.SvgElement;a.elementType=i.SvgElementType.Text,a.x=t,a.y=e,a.text=n,a.fontSize=o,l&&(a.fontWeight=l),g&&(a.fill=g),this.elements."
    "push(a)},t.prototype.toString=function(){var t='<svg viewBox=\"0 0 '.concat(this.width,\" \").concat(this.height,'\" "
    "xmlns=\"http://www.w3.org/2000/svg\">');"
    "this.textFont&&(t+=\"<style>\\n  text { font-family: \".concat(this.textFont,\";}\\n</style>\")"
    ");for(var e=0,n=this.elements;e<n.length;e++){var "
    "r=n[e];switch(r.elementType){case i.SvgElementType.Rectangle:t+='<rect x=\"'.concat(r.x,'\" y=\"').concat(r.y,'\" "
    "width=\"').concat(r.width,'\" height=\"').concat(r.height,'\"'),r.fill&&(t+=' fill=\"'.concat(r.fill,'\"')),t+=\" />\";break;case "
    "i.SvgElementType.Circle:t+='<circle cx=\"'.concat(r.x,'\" cy=\"').concat(r.y,'\" r=\"').concat(r.r,'\"'),r.fill&&(t+=' "
    "fill=\"'.concat(r.fill,'\"')),r.stroke&&(t+=' stroke=\"'.concat(r.stroke,'\"')),r.strokeWidth&&(t+=' "
    "stroke-width=\"'.concat(r.strokeWidth,'\"')),t+=\" />\";break;case i.SvgElementType.Text:t+='<text x=\"'.concat(r.x,'\" "
    "y=\"').concat(r.y,'\" font-family=\"').concat(this.textFont,'\" '),r.fill&&(t+=' fill=\"'.concat(r.fill,'\"')),r.fontWeight&&(t+=' "
    "font-weight=\"'.concat(r.fontWeight,'\"')),r.fontSize&&(t+=' font-size=\"'.concat(r.fontSize,'\"')),t+=\">\".concat(r.text,\"</text> "
    "/>\");break;case i.SvgElementType.Line:t+='<line x1=\"'.concat(r.x,'\" y1=\"').concat(r.y,'\" x2=\"').concat(r.x2,'\" "
    "y2=\"').concat(r.y2,'\"'),r.fill&&(t+=' fill=\"'.concat(r.fill,'\"')),r.stroke&&(t+=' "
    "stroke=\"'.concat(r.stroke,'\"')),r.strokeWidth&&(t+=' stroke-width=\"'.concat(r.strokeWidth,'\"')),t+=\" />\"}}return "
    "t+\"</svg>\"},t}();e.SvgImage=o},275:function(t,e,n){var r,i=this&&this.__extends||(r=function(t,e){return "
    "r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in "
    "e)Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n])},r(t,e)},function(t,e){if(\"function\"!=typeof e&&null!==e)throw new "
    "TypeError(\"Class extends value \"+String(e)+\" is not a constructor or null\");function "
    "n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new "
    "n)});Object.defineProperty(e,\"__esModule\",{value:!0}),e.AirRifle=void 0;var o=n(303),g=n(932),l=function(t){function e(e){var "
    "n=t.call(this,e)||this;return "
    "n.targetSize=80,n.rifleBlackRings=4,n.solidInnerTenRing=!0,n.outterRing=45.5,n.ring2=40.5,n.ring3=35.5,n.ring4=30.5,n.ring5=25.5,n."
    "ring6=20.5,n.ring7=15.5,n.ring8=10.5,n.ring9=5.5,n.ring10=.5,n.ringsRifle=[n.outterRing,n.ring2,n.ring3,n.ring4,n.ring5,n.ring6,n."
    "ring7,n.ring8,n.ring9,n.ring10],n.pelletCaliber=e,n.innerTenRadiusRifle=n.pelletCaliber/2-n.ring10/2,n}return "
    "i(e,t),e.prototype.getTargetType=function(){return g.TargetType.AirRifle},e.prototype.getProjectileCaliber=function(){return "
    "this.pelletCaliber},e.prototype.getSize=function(){return this.targetSize},e.prototype.getRings=function(){return "
    "this.ringsRifle},e.prototype.getOutterRing=function(){return this.outterRing},e.prototype.getOutterRadius=function(){return "
    "this.getOutterRing()/2+this.pelletCaliber/2},e.prototype.get10Radius=function(){return "
    "this.ring10/2+this.pelletCaliber/2},e.prototype.getInnerTenRadius=function(){return "
    "this.innerTenRadiusRifle},e.prototype.getBlackRings=function(){return "
    "this.rifleBlackRings},e.prototype.getBlackDiameter=function(){return this.ring4},e.prototype.isSolidInner=function(){return "
    "this.solidInnerTenRing},e.prototype.getRingTextCutoff=function(){return 8},e.prototype.getTextOffset=function(t,e){return "
    "0},e.prototype.getTextRotation=function(){return 0},e.prototype.getFirstRing=function(){return "
    "1},e.prototype.drawEastText=function(){return!0},e.prototype.drawNorthText=function(){return!0},e.prototype.drawSouthText=function(){"
    "return!0},e.prototype.drawWestText=function(){return!0},e.prototype.getFontSize=function(t){return "
    "t/8},e}(o.aTarget);e.AirRifle=l},775:function(t,e,n){var r,i=this&&this.__extends||(r=function(t,e){return "
    "r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in "
    "e)Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n])},r(t,e)},function(t,e){if(\"function\"!=typeof e&&null!==e)throw new "
    "TypeError(\"Class extends value \"+String(e)+\" is not a constructor or null\");function "
    "n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new "
    "n)});Object.defineProperty(e,\"__esModule\",{value:!0}),e.Rifle50m=void 0;var o=n(303),g=n(932),l=function(t){function e(e){var "
    "n=t.call(this,e)||this;return "
    "n.targetSize=250,n.rifleBlackRings=4,n.solidInnerTenRing=!1,n.outterRing=154.4,n.ring2=138.4,n.ring3=122.4,n.ring4=106.4,n.ring5=90.4,"
    "n.ring6=74.4,n.ring7=58.4,n.ring8=42.4,n.ring9=26.4,n.ring10=10.4,n.innerRing=5,n.blackCircle=112.4,n.ringsRifle=[n.outterRing,n."
    "ring2,n.ring3,n.ring4,n.ring5,n.ring6,n.ring7,n.ring8,n.ring9,n.ring10,n.innerRing],n.pelletCaliber=e,n.innerTenRadiusRifle=n."
    "innerRing/2+n.pelletCaliber/2,n}return i(e,t),e.prototype.getBlackRings=function(){return "
    "this.rifleBlackRings},e.prototype.getInnerTenRadius=function(){return "
    "this.innerTenRadiusRifle},e.prototype.getOutterRadius=function(){return "
    "this.getOutterRing()/2+this.pelletCaliber/2},e.prototype.get10Radius=function(){return "
    "this.ring10/2+this.pelletCaliber/2},e.prototype.getTargetType=function(){return "
    "g.TargetType.Rifle50m},e.prototype.getOutterRing=function(){return "
    "this.outterRing},e.prototype.getProjectileCaliber=function(){return this.pelletCaliber},e.prototype.getRings=function(){return "
    "this.ringsRifle},e.prototype.getSize=function(){return this.targetSize},e.prototype.isSolidInner=function(){return "
    "this.solidInnerTenRing},e.prototype.getFontSize=function(t){return t/6},e.prototype.getBlackDiameter=function(){return "
    "this.blackCircle},e.prototype.getRingTextCutoff=function(){return 8},e.prototype.getTextOffset=function(t,e){return "
    "3!=e?0:t/12},e.prototype.getTextRotation=function(){return 0},e.prototype.getFirstRing=function(){return "
    "1},e.prototype.drawEastText=function(){return!0},e.prototype.drawNorthText=function(){return!0},e.prototype.drawSouthText=function(){"
    "return!0},e.prototype.drawWestText=function(){return!0},e}(o.aTarget);e.Rifle50m=l},932:(t,e)=>{var "
    "n;Object.defineProperty(e,\"__esModule\",{value:!0}),e.TargetType=void "
    "0,function(t){t[t.AirRifle=0]=\"AirRifle\",t[t.Rifle50m=1]=\"Rifle50m\"}(n||(e.TargetType=n={}))},303:(t,e,n)=>{Object.defineProperty("
    "e,\"__esModule\",{value:!0}),e.aTarget=void 0;var r=n(290),i=n(227),o=n(932),g=function(){function "
    "t(t){this.caliber=t,this.textAngles=[]}return t.prototype.getName=function(){return "
    "o.TargetType[this.getTargetType()]},t.prototype.getScore=function(t){return "
    "11-t/this.get10Radius()},t.prototype.paintTarget=function(){this.isSolidInner(),this.getBlackRings();var "
    "t,e,n=this.getRings();this.drawEastText()&&this.textAngles.push(0),this.drawNorthText()&&this.textAngles.push(Math.PI/"
    "2),this.drawWestText()&&this.textAngles.push(Math.PI),this.drawSouthText()&&this.textAngles.push(3*Math.PI/2);var o=new "
    "i.Settings;t=10*this.getSize(),e=t/2;var g=new "
    "r.SvgImage(t,t);g.textFont=o.svgImageTextFont,g.addRectangle(0,0,t,t,o.svgImageBackgroundColor);for(var "
    "l=this.getFirstRing(),a=function(t){var r,i=void "
    "0,a=c.getBlackDiameter();t>0&&n[t-1]>a&&n[t]<a&&g.addCircle(e,e,10*a/2,o.svgImageForegroundColor);var "
    "s=n[t];s>a?(r=o.svgImageBackgroundColor,i=o.svgImageForegroundColor):(r=o.svgImageForegroundColor,i=o.svgImageBackgroundColor);var "
    "u=s/2;if(g.addCircle(e,e,10*u,r,i,2),l<=c.getRingTextCutoff()){var p=l.toString();if(l<=10)if(t+1==n.length);else{var "
    "f=s-n[t+1],h=18*c.getFontSize(f),y=10*c.getBlackDiameter()/2;c.textAngles.forEach((function(t){var "
    "n=10*(u-f/4.5),i=Math.cos(t)*n-h/4,l=Math.sin(t)*n+h/"
    "2.5;r=n>y?o.svgImageForegroundColor:o.svgImageBackgroundColor,g.addText(e+i,e+l,p,h,r,\"bold\")}))}}l++},c=this,s=0;s<n.length;s++)a("
    "s);return g.toString()},t}();e.aTarget=g}},i={};function o(t){var e=i[t];if(void 0!==e)return e.exports;var "
    "n=i[t]={exports:{}};return r[t].call(n.exports,n,n.exports,o),n.exports}e=o(275),n=o(775),o(290),t=new "
    "e.AirRifle(4.5).paintTarget(),document.querySelector(\"div.svg.airRifle\").innerHTML=t,t=new "
    "n.Rifle50m(5.6).paintTarget(),document.querySelector(\"div.svg.rifle50m\").innerHTML=t})();"
    "</script>"
    "</body>"
    "</html>";