const char post_test_2_html[] = "<!DOCTYPE html>"
                                "<html>"
                                "<head>"
                                "<script>"
                                "function onButtonClick() {"
                                "let url = document.getElementById(\"url\").value;"
                                "let data = document.getElementById(\"jsonData\").value;"
                                "fetch(url, {"
                                "method: 'POST',"
                                "headers: {"
                                "'Content-Type': 'application/json'"
                                "},"
                                "body: data"
                                "})"
                                ".then(response => alert(\"return status: \" + response.status))"
                                ".catch(error => alert(\"error : \" + error));"
                                "}"
                                "</script>"
                                "</head>"
                                "<body>"
                                "Url:<br />"
                                "<input type=\"text\" id=\"url\" size=\"50\" value=\"http://192.168.1.120/something\" /><br />"
                                "<br />"
                                "JSON data:<br />"
                                "<textarea id=\"jsonData\" rows=\"10\" cols=\"50\">{\"name\":\"Ole\"}</textarea><br />"
                                "<br />"
                                "<button onclick=\"onButtonClick()\">POST Json data to url</button>"
                                "</body>"
                                "</html>";
